/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "DISCORD_FEEDBACK_BOT_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "POSTHOG_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Web": {
      "type": "sst.cloudflare.SolidStart"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}