/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

import "sst"
declare module "sst" {
  export interface Resource {
    "Web": {
      "type": "sst.cloudflare.SolidStart"
      "url": string
    }
  }
}

import "sst"
export {}